
name: "Build Release"

on: release

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Test on ${{ matrix.os }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, windows-11-arm, macos-13, macos-latest]
        python-version: ['3.14']
        # exclude:
        #   - os: windows-11-arm  # setup-python action only supports 3.11+
        #     python-version: '3.9'
        #   - os: windows-11-arm  # setup-python action only supports 3.11+
        #     python-version: '3.10'
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          check-latest: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        # Time for the change we now want to build a C Library instead of a python wheel...
        run: python -m pip install -r requirements-dev.txt

      - name: "Build Packages"
        # Use our custom command-line to point to a directory to release the data to for easy uploading...
        run: python build_release.py --dir dist
      

      # TODO: I'll ask a few people how to shove these releases into Releases Page on github...
      - uses: actions/upload-artifact@v6
        with:
          name: llh2-*
          path: dist/*.

      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/llh2-*
            LICENSE
